name: 自动更新 Fork
on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动更新
  workflow_dispatch:      # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: zwping/fork-sync@v1.6.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
